project_id = "vegvmdmfegsdjukbiqam"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "https://5de88b8f-4fec-4c14-bb58-b53356abcbde.sandbox.lovable.dev"
additional_redirect_urls = ["https://localhost:3000", "https://quickwriteaiapp.netlify.app", "https://quickwriteaiapp.netlify.app/app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
security_refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 6

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"

[edge-runtime]
enabled = true
port = 54323

[functions.generate-content]
verify_jwt = false

[functions.expire-subscriptions]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.create-dodo-checkout]
verify_jwt = true

[functions.dodo-webhook]
verify_jwt = false

[functions.admin-operations]
verify_jwt = false
